version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    target-branch: 'main'
    labels:
      - 'master'
    pull-request-branch-name:
      separator: '-'
    commit-message:
      prefix: '(fix) update'
    open-pull-requests-limit: 10
    reviewers:
      - 'pip77'
      - 'marionfischer'
