version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      day: "monday"
      time: "08:30"
      timezone: "CET"
    target-branch: "main"
    labels:
      - "Dependabot"
    pull-request-branch-name:
      separator: "-"
    commit-message:
      prefix: "(fix) update"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    open-pull-requests-limit: 10
    # Disable rebasing for npm pull requests
    rebase-strategy: "disabled"
